baseURL = "/"
languageCode = "de"
title = "Docker"
theme = "coder"

[params]
  author = "Bernd √ñggl, Michael Kofler"
  info = "Ein Buch √ºber Docker f√ºr DevOps"
  description = "Beispiele, Cloud und viel mehr"
  avatarurl = "images/dc_s.png"
  hideCredits = true
  hideCopyright = false

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/docbuc/"
    icon = "fa fa-github"
[[params.social]]
    name = "Amazon"
    weight = 2
    icon = "fa fa-amazon"
    url = "https://www.amazon.de/Docker-Praxisbuch-Entwickler-DevOps-Teams-Windows/dp/3836261766/"
[[params.social]]
    name = "Rheinwerk"
    weight = 2
    url = "https://www.rheinwerk-verlag.de/docker_4599/"
[[params.social]]
    name = "üêò b√∂"
    weight = 3
    url = "https://webmapping.social/@bernd"
    rel = "me"
[[params.social]]
    name = "üêò mk"
    weight = 3
    url = "https://home.social/@michaelkofler"

# [[menu.main]]
#   name = "Blog"
#   weight = 1
#   url = "/posts/"
[[menu.main]]
  name = "Inhalt"
  weight = 2
  url = "/inhalt/"
[[menu.main]]
  name = "Errata"
  weight = 3
  url = "https://kofler.info/buecher/docker/errata/"
[[menu.main]]
  name = "√úber das Buch"
  weight = 4
  url = "/about/"
