services:
  mariadb:
    image: mariadb:lts
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: db1
    volumes:
      - mariavol:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
      - ./myown.cnf:/etc/mysql/conf.d/myown.cnf

volumes:
  mariavol:
