# note: does not work with podman compose (tested with Podman 5.6, Podman Desktop and docker compose v2.39.3
services:
  secrettest:
    image: alpine
    secrets:
      - mypassword
    command: ["cat", "/run/secrets/mypassword"]

secrets:
  mypassword:
    file: ./top-secret.txt
