entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'
    transport:
      respondingTimeouts:
        readTimeout: '30m'
        writeTimeout: '30m'
        idleTimeout: '5m'
api:
  dashboard: true
certificatesResolvers:
  lets-encrypt:
    acme:
      email: info@dockerbuch.info
      storage: /acme/acme.json
      tlsChallenge: {}
providers:
  docker:
    watch: true
    network: web
  file:
    filename: traefik_api.yml

