services:
  grafana:
    image: grafana/grafana:12.2
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=geheim
    volumes:
      - grafana:/var/lib/grafana
  telegraf:
    image: telegraf:1.36
    hostname: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
  influx:
    image: influxdb:2.7
    restart: always
    volumes:
      - influx:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=dockerbuch
      - DOCKER_INFLUXDB_INIT_PASSWORD=geheimgeheim
      - DOCKER_INFLUXDB_INIT_ORG=dockerbuch
      - DOCKER_INFLUXDB_INIT_BUCKET=dockerbuch
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=gahPae6deivo0aenooy7thoheewaex9eeNgaePah8dee5io6neewooSe3bemu9gi
volumes:
  influx:
  grafana:

