services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      # Enable Docker provider
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # Entry points
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # HTTP to HTTPS redirect
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      # Let's Encrypt
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    ports:
      # port 80 for Let's Encrypt
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
      # for alert manager
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--web.external-url=https://prometheus.example.com'
      # these settings are used per default anyway
      # - '--web.console.libraries=/etc/prometheus/console_libraries'
      # - '--web.console.templates=/etc/prometheus/consoles'
      # - '--web.route-prefix=/'
    labels:
      - traefik.enable=true
      - traefik.http.services.prometheus.loadbalancer.server.port=9090
      - traefik.http.routers.prometheus.rule=Host(`prometheus.example.com`)
      - traefik.http.routers.prometheus.tls=true
      - traefik.http.routers.prometheus.tls.certresolver=letsencrypt
      - traefik.http.routers.prometheus.middlewares=prometheus-auth
      # todo, name:$$hash$$code einbauen
      - traefik.http.middlewares.prometheus-auth.basicauth.users=...
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
      - 127.0.0.1:9093:9093

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      # todo: initial password for Grafana admin
      - GF_SECURITY_ADMIN_PASSWORD=xxx
      - GF_SERVER_ROOT_URL=https://grafana.example.com
    labels:
      - traefik.enable=true
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.http.routers.grafana.rule=Host(`grafana.example.com`)
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=letsencrypt
      - traefik.http.routers.grafana.middlewares=grafana-auth
      # todo, name:$$hash$$code einbauen
      - traefik.http.middlewares.grafana-auth.basicauth.users=...
    restart: unless-stopped

  # Node Exporter for localhost / Docker host (self monitoring)
  nodeexporter:
    image: prom/node-exporter:latest
    container_name: nodeexporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  # web monitoring
  blackboxexporter:
    image: prom/blackbox-exporter:latest
    container_name: blackboxexporter
    ports:
      - "127.0.0.1:9115:9115"
    volumes:
      - ./blackbox.yml:/config/blackbox.yml
    command:
      - "--config.file=/config/blackbox.yml"
  
volumes:
  prometheus-data:
  grafana-data:

networks:
  default:
    name: traefik
