services:
  gitlab:
    hostname: gitlab.dockerbuch.info
    image: gitlab/gitlab-ce:latest
    environment:
      GITLAB_ROOT_PASSWORD: GanzGeheimGanz
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.dockerbuch.info/'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
        postgresql['enable'] = false
        gitlab_rails['db_host'] = 'postgresql'
        gitlab_rails['db_port'] = '5432'
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['db_password'] = 'ief6baehohQu'
        gitlab_rails['db_database'] = 'gitlab_prod'
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        redis['enable'] = false
        gitlab_rails['redis_host'] = 'redis'
        gitlab_rails['redis_port'] = '6379'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'none'
        gitlab_rails['smtp_address'] = 'exim'
        gitlab_rails['smtp_port'] = 25
        gitlab_rails['gitlab_email_from'] = 'gl@dockerbuch.info'
        registry_external_url 'https://registry.dockerbuch.info'
        registry['registry_http_addr'] = "0.0.0.0:5000"
        registry_nginx['enable'] = false
        # registry['max_upload_size'] >= 10737418240
        mattermost_external_url 'https://mattermost.dockerbuch.info'
        mattermost_nginx['enable'] = false
        mattermost['gitlab_enable'] = true
        mattermost['service_address'] = "0.0.0.0"
        mattermost['service_port'] = "8065"
        mattermost['gitlab_id'] = "b21953057d316aa0eb7bd1d36d647554b8463c20f8dd11d86804f42813b2093d"
        mattermost['gitlab_secret'] = "gloas-d140425cb3c522c6b39fe76df21fc95c5c28257086bf5996f0ca90ec81cb3041"
        mattermost['gitlab_scope'] = "read_user"
        mattermost['gitlab_auth_endpoint'] = "http://gitlab.dockerbuch.info/oauth/authorize"
        mattermost['gitlab_token_endpoint'] = "http://gitlab.dockerbuch.info/oauth/token"
        mattermost['gitlab_user_api_endpoint'] = "http://gitlab.dockerbuch.info/api/v4/user"
        gitlab_rails['mattermost_host'] = "https://mattermost.dockerbuch.info"
        mattermost['sql_driver_name'] = 'postgres'
        mattermost['sql_data_source'] = "user=gitlab_mattermost host=postgresql port=5432 sslmode=disable dbname=mattermost password=geheim"
    ports:
      - "2222:22"
    restart: unless-stopped
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
    networks:
      - web
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitlab.rule=Host(`gitlab.dockerbuch.info`)
      - traefik.http.routers.gitlab.tls=true
      - traefik.http.routers.gitlab.tls.certresolver=lets-encrypt
      - traefik.http.services.gitlab.loadbalancer.server.port=80
      - traefik.http.routers.gitlab.service=gitlab
      - traefik.http.routers.reg.rule=Host(`registry.dockerbuch.info`)
      - traefik.http.routers.reg.tls=true
      - traefik.http.routers.reg.tls.certresolver=lets-encrypt
      - traefik.http.routers.reg.service=gl-rg
      - traefik.http.middlewares.registry-body.buffering.maxRequestBodyBytes=2147483648
      - traefik.http.services.gl-rg.loadbalancer.server.port=5000

      - "traefik.http.middlewares.registry-body.buffering.maxRequestBodyBytes=2147483648"  # 2GB
      - "traefik.http.middlewares.registry-body.buffering.maxResponseBodyBytes=2147483648"  # 2GB
      - "traefik.http.middlewares.registry-body.buffering.memRequestBodyBytes=10485760"  # 10MB
      - "traefik.http.middlewares.registry-body.buffering.retryExpression=IsNetworkError() && Attempts() < 3"
      # Apply middleware
      # - "traefik.http.routers.registry.middlewares=registry-body"
      - traefik.http.routers.reg.middlewares=registry-body

      # Service configuration with increased timeouts
      # - "traefik.http.services.registry.loadbalancer.server.port=5000"
      # - "traefik.http.services.gl-rg.loadbalancer.healthCheck.interval=30s"
      # - "traefik.http.services.gl-rg.loadbalancer.healthCheck.timeout=10s"



      - traefik.http.routers.mm.rule=Host(`mattermost.dockerbuch.info`)
      - traefik.http.routers.mm.tls=true
      - traefik.http.routers.mm.tls.certresolver=lets-encrypt
      - traefik.http.routers.mm.service=mm
      - traefik.http.services.mm.loadbalancer.server.port=8065
  redis:
    image: redis:8
    restart: unless-stopped
  postgresql:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gitlab
      - POSTGRES_PASSWORD=ief6baehohQu
      - POSTGRES_DB=gitlab_prod
    volumes:
      - pgdata:/var/lib/postgresql/data
  exim:
    build: exim/
    restart: unless-stopped
    environment:
      - RELAY_FROM=gitlab-gitlab-1.gitlab_default
volumes:
  config:
  logs:
  data:
  pgdata:

networks:
  web:
    external: true

