apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: telegraf
  name: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: telegraf
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: telegraf
    spec:
      containers:
        - env:
            - name: INFLUXDB_BUCKET
              value: dockerbuch
            - name: INFLUXDB_ORG
              value: dockerbuch
            - name: INFLUXDB_TOKEN
              value: gahPae6deivo0aenooy7thoheewaex9eeNgaePah8dee5io6neewooSe3bemu9gi
          image: docbuc/telegraf:5
          name: telegraf
      restartPolicy: Always
