---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o kube.yaml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: api
  name: api
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: api

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o kube.yaml
    kompose.service.type: nodeport
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
  selector:
    io.kompose.service: frontend
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o kube.yaml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: mongo1
  name: mongo1
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongo1

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o kube.yaml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: mongo2
  name: mongo2
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongo2

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o kube.yaml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: mongo3
  name: mongo3
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongo3

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o kube.yaml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: redis
  name: redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o kube.yaml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml -o kube.yaml
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: DEBUG
              value: api
            - name: HEALTH_URL
              value: http://localhost:3000/health
            - name: MONGO_URL
              value: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=rs0
          image: docbuc/mwa-api
          name: api
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o kube.yaml
    kompose.service.type: nodeport
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml -o kube.yaml
        kompose.service.type: nodeport
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - image: docbuc/mwa-fe
          name: frontend
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o kube.yaml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: mongo1
  name: mongo1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml -o kube.yaml
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: mongo1
    spec:
      containers:
        - args:
            - --replSet
            - rs0
          image: mongo:8
          name: mongo1
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: /data/db
              name: mongovol1
      restartPolicy: Always
      volumes:
        - name: mongovol1
          persistentVolumeClaim:
            claimName: mongovol1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mongovol1
  name: mongovol1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o kube.yaml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: mongo2
  name: mongo2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo2
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml -o kube.yaml
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: mongo2
    spec:
      containers:
        - args:
            - --replSet
            - rs0
          image: mongo:8
          name: mongo2
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: /data/db
              name: mongovol2
      restartPolicy: Always
      volumes:
        - name: mongovol2
          persistentVolumeClaim:
            claimName: mongovol2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mongovol2
  name: mongovol2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o kube.yaml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: mongo3
  name: mongo3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo3
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml -o kube.yaml
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: mongo3
    spec:
      containers:
        - args:
            - --replSet
            - rs0
          image: mongo:8
          name: mongo3
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: /data/db
              name: mongovol3
      restartPolicy: Always
      volumes:
        - name: mongovol3
          persistentVolumeClaim:
            claimName: mongovol3

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mongovol3
  name: mongovol3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o kube.yaml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml -o kube.yaml
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: redis
    spec:
      containers:
        - image: redis:8-alpine
          name: redis
          ports:
            - containerPort: 6379
              protocol: TCP
      restartPolicy: Always

