# Datei: db/mongo-auth/compose.yaml
services:
  db:
    image: mongo:8
    volumes:
      - mongo:/data/db
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: geonames
      MONGO_INITDB_ROOT_USERNAME: dockerbuch
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_root
    secrets:
      - mongo_root
volumes:
  mongo:
secrets:
  mongo_root:
    file: ./mongo_root.txt

